services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=lab'
      - 'POSTGRES_PASSWORD=belcaid2001'
      - 'POSTGRES_USER=belcaid'
    ports:
      - '5432:5432'
    networks:
      - 'spring-cloud-network'

networks:
  spring-cloud-network:
    driver: bridge


