services:
  lab-management-system:
    container_name: lab-management-system-container
    build:
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: lab-management-system:v1
    restart: unless-stopped
    expose:
      - ${CONTAINER_PORT}
    ports:
      - ${CONTAINER_PORT}:${HOST_PORT}

