# Development Profile Configuration

# Database configuration for PostgreSQL
DB_TYPE: postgres  # postgresql       # Database type
DB_USERNAME: belcaid      # Database username
DB_PASSWORD: DHa7mYfAdl1zxYOyWi7ybQkEx59xegOx  # Database password
DB_HOST: dpg-ckemntdtj22c7389q29g-a        # Database host
DB_PORT: 5432             #5432             # Database port
DB_NAME: lab_tr8y   # Database name
DB_DRIVER: org.postgresql.Driver  # Database driver class
DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect  # Hibernate dialect for PostgreSQL

# Server port configuration
SERVER_PORT: 8080  # Port on which the server will run

# Active Spring profile (development)
ACTIVE_PROFILE: dev

# Mail configuration
MAIL_USERNAME: abdellahbalkaid49@gmail.com  # Email account username
MAIL_PASSWORD: beulsfszvrkslspt              # Email account password
MAIL_VERIFY_HOST: http://localhost:8080      # Verification host URL for email verification

# JWT (JSON Web Token) configuration
JWT_SECRET: 77397A24432646294A404E635266556A586E327235753878214125442A472D4B  # Secret key for JWT tokens
JWT_EXPIRATION_MS: 86400000  # JWT expiration time in milliseconds (24 hours)

# Internal API key for authentication purposes
INTERNAL_API_KEY: InternalApiKey1234!
